FROM postgres:latest

# Define as variáveis de ambiente para o banco de dados
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_DB=ms-user

EXPOSE 5432

# docker build -t my-postgres .
# docker run -d --name postgres-container -p 5432:5432 my-postgres